### PR TITLE
Added support for STA with absoulte addressing

### PR DESCRIPTION
**Pull request by ml85**
Does it look right?

### CODE REVIEW

**Comment by robinlinden** [comment]
Yeah, I think it looks good, and this agrees with your implementation:
```
     Write instructions (STA, STX, STY, SAX)

        #  address R/W description
       --- ------- --- ------------------------------------------
        1    PC     R  fetch opcode, increment PC
        2    PC     R  fetch low byte of address, increment PC
        3    PC     R  fetch high byte of address, increment PC
        4  address  W  write register to effective address
```

**Comment by johnor** [comment]
The implementation looks good! I've been thinking how we should handle similar operations and addressing modes. What do you think about creating an addressing mode factory that can add stages to the pipeline for a mode, since those parts of the pipeline will be the same for many instructions? I'm also thinking about splitting decoding of an opcode into op and addressing mode. What do you guys think?

**Comment by robinlinden** [comment]
I think that's a great idea. :) Even the docs usually bundle a bunch of instructions since a lot of them are the same aside from what they're reading/writing, for example:
`Write instructions (STA, STX, STY)`
`Read instructions (LDA, LDX, LDY, NOP)`

Some have special side-effects, but most are really really similar.

**Comment by ml85** [comment]
Yes, I agree. We need to do something here to not get a lot of duplicated code. Some kind of factory sounds good. An opcode migth be a struct with a code and an addressing mode.

**Pull request merged**
