### PR TITLE
Add branching instructions

### PR DESCRIPTION
**Pull request by robinlinden**
Since all of these are more or less identical, I figured I'd implement one and get some eyes on it before finishing the rest.

```
Relative addressing (BCC, BCS, BNE, BEQ, BPL, BMI, BVC, BVS)

        #   address  R/W description
       --- --------- --- ---------------------------------------------
        1     PC      R  fetch opcode, increment PC
        2     PC      R  fetch operand, increment PC
        3     PC      R  Fetch opcode of next instruction,
                         If branch is taken, add operand to PCL.
                         Otherwise increment PC.
        4+    PC*     R  Fetch opcode of next instruction.
                         Fix PCH. If it did not change, increment PC.
        5!    PC      R  Fetch opcode of next instruction,
                         increment PC.

       Notes: The opcode fetch of the next instruction is included to
              this diagram for illustration purposes. When determining
              real execution times, remember to subtract the last
              cycle.

              * The high byte of Program Counter (PCH) may be invalid
                at this time, i.e. it may be smaller or bigger by $100.

              + If branch is taken, this cycle will be executed.

              ! If branch occurs to different page, this cycle will be
                executed.
```

### CODE REVIEW

**Comment by johnor** [comment]
It looks like the branching instructions take different number of cycles depending on if the branch was taken or not, and if the branch is to a different page. Should we try and emulate that as well?

**Comment by robinlinden** [comment]
Yes, we definitely should. The whole fixing the high byte of the stack
pointer is missing from this PR right now. I think we should try to be
cycle accurate as far as we can. I'm sure there are games that count on
things being exactly as they are on the NES, bugs and all.

**Comment by robinlinden** [comment]
I tried using auto at first, but that fails compilation with the error
```
n_e_s/core/src/mos6502.cpp: In member function 'virtual void n_e_s::core::Mos6502::execute()':
n_e_s/core/src/mos6502.cpp:110:74: error: use of 'auto n_e_s::core::Mos6502::branch_on(std::function<bool()>)' before deduction of 'auto'
                     branch_on([=]() { return !(registers_->p & N_FLAG); }));
                                                                          ^
n_e_s/core/src/mos6502.cpp:117:71: error: use of 'auto n_e_s::core::Mos6502::branch_on(std::function<bool()>)' before deduction of 'auto'
                     branch_on([=]() { return registers_->p & N_FLAG; }));
```

**Comment by ml85** [comment]
Oh I missed that this is a member function, hard to review on the phone :). In that case I guess the implementation needs to be in the header file, but that's ugly!

**Comment by robinlinden** [comment]
Right, I've added all branching instructions and tests for them, so I think this is ready for review/merge. :)

**Pull request merged**
